import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { IndexPage } from '@/ui/pages/root/IndexPage'
import Home from '@/app/page'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

import { colors } from '@/constants'
import { StateWrap } from '@/app/_state'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        style={{
          background: 'white',
          width: '100%',
          height: '100%',
          padding: 0,
          margin: 0
        }}
      >
        <StateWrap>{children}</StateWrap>
      </body>
    </html>
  )
}
