import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UrlPage } from '@/ui/pages/Url/UrlPage'
import Home from '@/app/page'
import React from 'react'
import { headers } from 'next/headers'
const inter = Inter({ subsets: ['latin'] })

import { colors } from '@/constants'
import { StateWrap } from '@/app/_state'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = headers()
  const acceptLanguage = headersList.get('accept-language') || 'en'
  const lang = acceptLanguage.split(',')[0]
  return (
    <html lang={lang}>
      <head></head>
      <body
        style={{
          background: 'white',
          width: '100%',
          height: '100%',
          padding: 0,
          margin: 0
        }}
      >
        <StateWrap>{children}</StateWrap>
      </body>
    </html>
  )
}
